name: CD

on:
  push:
    branches:
      - 'release/**'   

jobs:
  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sources/

    steps:
    - uses: actions/checkout@v3

    - name: Find release version
      uses: actions/github-script@v6
      id: version
      with:
        script: |
          const version = context.ref.replace('refs/heads/release/', '')
          const parts = version.split('-')
          return { prefix: parts[0], suffix: parts[1] || '' }
    - name: Set release version prefix
      run: echo "VERSION_PREFIX=${{ fromJSON(steps.version.outputs.result).prefix }}" >> $GITHUB_ENV
    - name: Set release version suffix
      run: echo "VERSION_SUFFIX=${{ fromJSON(steps.version.outputs.result).suffix }}" >> $GITHUB_ENV
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:VersionPrefix=${{ env.VERSION_PREFIX }} -p:VersionSuffix=${{ env.VERSION_SUFFIX }}
    - name: Pack
      run: dotnet pack --output nupkgs --no-build -p:VersionPrefix=${{ env.VERSION_PREFIX }} -p:VersionSuffix=${{ env.VERSION_SUFFIX }}
