name: CD

on:
  push:
    branches:
      - 'release/**'   

jobs:
  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sources/

    steps:
    - name: Set release version
      uses: actions/github-script@v6
      id: release_version
      with:
        script: return context.ref.replace('refs/heads/release/', '')
        result-encoding: string
    - name: Print release version
      run: echo ${{ steps.release_version.outputs.result }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Build
      run: dotnet pack -p:Version=${{ steps.release_version.outputs.result }}
