name: CI

on:
  push:
    branches-ignore:
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sources/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:VersionPrefix=0.0.0
    - name: Test
      id: tests
      run: dotnet test --no-build --verbosity normal
    - name: Failed functional tests artifacts
      uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.tests.conclusion == 'failure' }}
      with:
        name: FunctionalTestsFailsArtifacts
        path: ./sources/Heatmap.FunctionalTests/bin/Debug/net6.0/FunctionalTestsFailsArtifacts
